export const CORS_CREDENTIALS = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_URL,
};

export const TOKEN_CREDENTIALS = {
  JWT_ACCESS_SECRET: process.env.NEXT_PUBLIC_JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.NEXT_PUBLIC_JWT_REFRESH_SECRET,
};
